# Site settings
title: Miserere
email: erasmusdearos+miserere@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Short film Miserere. Directed by Erasmus de Aros.
twitter_description: Forgive, Highest, my sins
baseurl: "" # in development. For Github  ""
url: "http://miserere.xyz/" # the base hostname & protocol for your site
name: "Erasmus de Aros"

# Build settings
markdown: redcarpet
highlighter: rouge # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
